name: Cypress Tests
on: [push]
jobs:
   cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true 
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
           command:npm run test3
          wait-on: 'http://localhost:3000' 
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}